# .properties configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/blogdb?serverTimezone=GMT-5&characterEncoding=utf8
#
#spring.datasource.username=test
#
#spring.datasource.password=test
#
#spring.jackson.time-zone=GMT-5

# .yml configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogdbreal?serverTimezone=GMT-5&characterEncoding=utf8
    username: "test"
    password: "test"
server:
  tomcat:
#    basedir: "/home/ubuntu/"
    basedir: "D:/Blog"
